### ISSUE TITLE
Create membership plan(s) for VR festival

### ISSUE THREAD

**Issue by gusaus** [OpenProducer/angelcityjazz#19]
I took a first pass at creating memberships for all VR events. We can create them on this instance and then import to our staging environment when ready.

All the products are displayed here - 
https://commerce-angelcityjazz.pantheonsite.io/wp-admin/edit.php?product_cat=concerts&post_type=product

## Product attributes
Elements include the following -

### Title
![Edit Membership Plan ‹ Angel City Jazz — WordPress 2020-08-25 13-49-27](https://user-images.githubusercontent.com/113996/91226479-f15e4400-e6d9-11ea-92eb-a6cce6e46599.png)
- probably something like this (assuming each product needs a membership plan)
#### General 
![Edit Membership Plan ‹ Angel City Jazz — WordPress 2020-08-25 13-54-00](https://user-images.githubusercontent.com/113996/91226854-7184a980-e6da-11ea-858e-36e9aba05033.png)
- Grant access upon - product purchase
- Products - add associated product
- Membership length - need to determine what to select here 
  - specific length - is this length after purchase? what happens if access is purchased before the event?
  - fixed dates - we could associate the start date with the event/release date, but how about a purchase after the start date? what would be the end date/
#### Restrict Content 
![Edit Membership Plan ‹ Angel City Jazz — WordPress 2020-08-25 14-08-30](https://user-images.githubusercontent.com/113996/91228087-7d716b00-e6dc-11ea-992e-0c236888dac5.png)
- Type: Posts
- Title: add post where there's restricted content
- Accessible: immediately (?)
#### Restrict Products 
![Edit Membership Plan ‹ Angel City Jazz — WordPress 2020-08-25 14-10-43](https://user-images.githubusercontent.com/113996/91228238-c6292400-e6dc-11ea-92c5-108bc2412d1f.png)
- N/A
#### Purchasing Discounts 
![Edit Membership Plan ‹ Angel City Jazz — WordPress 2020-08-25 14-12-32](https://user-images.githubusercontent.com/113996/91228438-199b7200-e6dd-11ea-987c-8faafd197bc8.png)
- not sure we'd be providing discounts; should look into it
#### Members Area
![Edit Membership Plan ‹ Angel City Jazz — WordPress 2020-08-25 14-14-40](https://user-images.githubusercontent.com/113996/91228590-54050f00-e6dd-11ea-87f3-a3c5aa63bba5.png)
- We might want to customize these options and then duplicate for each membership
  - "Content" will show all pages, posts and other content.
  - "Products" will show products that are viewable or purchaseable.
  - "Discounts" will list products carrying membership discounts.
  - "Notes" will only display notes that have been emailed to the customer (no internal membership notes).
  - "Manage" will show details about the membership, such as status and action links.
####  Email Content 
![Edit Membership Plan ‹ Angel City Jazz — WordPress 2020-08-25 14-15-43](https://user-images.githubusercontent.com/113996/91228655-7a2aaf00-e6dd-11ea-9c5a-d6df4114816c.png)
- Still need to enable/configure emails

## Todo

- [ ] determine if we need to set up a membership plan for each event/product
- [ ] determine when access begins; after purchase? 
- [ ] determine how we can control access
